version: 2.1

jobs:
  rake_default:
    parameters:
      image:
        description: "Name of the Docker image."
        type: string
        default: "cimg/ruby:3.2"
    docker:
      - image: << parameters.image >>
    environment:
      # CircleCI container has two cores, but Ruby can see 32 cores. So we
      # configure test-queue.
      # See https://github.com/tmm1/test-queue#environment-variables
      TEST_QUEUE_WORKERS: 2
      JRUBY_OPTS: "--dev -J-Xmx1000M"
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

  # Miscellaneous tasks
  documentation-checks:
    docker:
      - image: cimg/ruby:3.2
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Check documentation syntax
          command: bundle exec rake documentation_syntax_check

workflows:
  build:
    jobs:
      - documentation-checks
      - rake_default:
          name: Ruby 2.7
          image: cimg/ruby:2.7
      - rake_default:
          name: Ruby 3.0
          image: cimg/ruby:3.0
      - rake_default:
          name: Ruby 3.1
          image: cimg/ruby:3.1
      - rake_default:
          name: Ruby 3.2
          image: cimg/ruby:3.2
      - rake_default:
          name: Ruby HEAD
          image: rubocophq/circleci-ruby-snapshot:latest # Nightly snapshot build
